language: cpp

matrix:
  include:
    - os: linux
      dist: bionic

before_install: 
  - wget -O - https://raw.githubusercontent.com/Pokerpoke/LeetCode/master/ci/build-googletest.sh | sh

before_script:
  - mkdir build && cd build
  - cmake ..

script:
  - make
  - make test